apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-deployment
  labels:
    app: consulta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulta
  template:
    metadata:
      labels:
        app: consulta
    spec:
      containers:
      - name: consulta
        image: consulta-service:latest 
        ports:
        - containerPort: 6000